from abc import ABC, abstractmethod
from datetime import date

class MarketDataProvider(ABC):
    @abstractmethod
    async def search_stock(self, keyword: str) -> list[dict]: ...
    @abstractmethod
    async def get_stock_basic(self, ts_code: str) -> dict: ...
    @abstractmethod
    async def get_daily_price(self, ts_code: str, start_date: date, end_date: date) -> list[dict]: ...
    @abstractmethod
    async def get_daily_valuation(self, ts_code: str, start_date: date, end_date: date) -> list[dict]: ...
    @abstractmethod
    async def get_income_statement(self, ts_code: str, periods: int) -> list[dict]: ...
    @abstractmethod
    async def get_balance_sheet(self, ts_code: str, periods: int) -> list[dict]: ...
    @abstractmethod
    async def get_cashflow_statement(self, ts_code: str, periods: int) -> list[dict]: ...
    @abstractmethod
    async def get_financial_indicators(self, ts_code: str, periods: int) -> list[dict]: ...
    @abstractmethod
    async def get_business_segments(self, ts_code: str) -> list[dict]: ...

